### PR TITLE
New feature: Map

### PR DESCRIPTION
**Pull request by sblaisot**
This Pull Request add a new page in White Pages showing the location of people on a world map, based on [leafletJS](https://leafletjs.com/) javascript library and OpenStreetMap maps. 

This feature is particularly useful for distributed teams.

image

The fllowing features have been implemented:
- Display point as default marker or markers with photo
- When two or more markers are too close from each other, they are combined into a clickable cluster marker
- Map page accept a `groupdn` parameter to limit map to a given team
- Clicking on a marker opens a detail popup with configurable content
- Configurable user filter for map
- Configurable OSM tile server and credits
- Configurable geocoding URL
- Geocoding cache with APCu module
- People without localizable address can be ignored (not shown on map) or placed on a default location

### CODE REVIEW

**Comment by coudot** [comment]
Thanks for this great proposition, I'll have a look as soon as possible

**Comment by artlog** [comment]
taking a look to test it.

**Comment by sblaisot** [comment]
Here is an export of my test ldap entries if this can be useful for your test:

[example.ldif.zip](https://github.com/ltb-project/white-pages/files/10332077/example.ldif.zip)

**Comment by artlog** [comment]
using Docker and provided example 
sudo docker build -t white-pages:map -f packaging/docker/Dockerfile .

i yet don't get any Map menu

image

still trying

**Comment by artlog** [comment]
i have no groups , it is the problem ?

**Comment by sblaisot** [comment]
maybe you should enable it to see the map menu by adding `$use_map = true;` in your `config.inc.local.php` (I added it disabled by default, this can be changed if needed).

See `docs/mapmenu.rst`

My test `config.inc.local.php` looks like:

```
<?php

# HTTP
$http_url="http://localhost";

# LDAP
$ldap_url = "ldap://localhost";
$ldap_starttls = false;
$ldap_binddn = "cn=admin,dc=company,dc=example";
$ldap_bindpw = "S3cr3tP@ssW0rd!";
$ldap_base = "dc=company,dc=example";
$ldap_user_base = "ou=people,".$ldap_base;
$ldap_user_filter = "(objectClass=inetOrgPerson)";

$use_map = true;

// PHP 8 compat
unset($search_result_sortby);
unset($gallery_sortby);
unset($directory_sortby);

$debug = true;
?>
```

**Comment by artlog** [comment]
Yes it was the obviously missing `$use_map = true;`
it just works.

This is fine that it is disabled by default.

**Comment by artlog** [comment]
image

It works just nicely.

**Comment by coudot** [comment]
Thanks a lot for this contribution, now merged into master.

**Pull request merged**
