### PR TITLE
Factorize search 

### PR DESCRIPTION
**Pull request by artlog**
latest factorization on top of ltb-project/ldap rebased on master.

### CODE REVIEW

**Comment by sblaisot** [comment]
I'm afraid map.php has been broken by this PR as it still requires ldap.inc.php tht has been removed.

**Comment by sblaisot** [comment]
same for `bin/map_preload_geocoding_cache.php`

**Comment by coudot** [comment]
Hello @sblaisot we indeed need to apply the changes to the new map feature.

**Comment by coudot** [comment]
@sblaisot it should be ok with my latest commit.

**Pull request merged**
