### PR TITLE
List view directory search

### LINKED ISSUE #1: Add pagination to results
For the moment all results are displayed in a single page

We should have pagination (different configuration between standard results and gallery)

The must would be to map the pagination to LDAP SSSVLV control to only query visible entries, with http://php.net/manual/en/function.ldap-control-paged-result.php

### LINKED ISSUE #16: Print results as rows or boxes
Hello,

It could be nice to have an option in config file to change display of results (rows or boxes). 

Advantages of rows results in comparison of boxes results : 
- you can print directly HTML page for end users;
- you can sort results by columns;
- you can display more information on results page;

Proposal : add a config option `display_results` in Full Display's section of `config.inc.php` with two values : 
- rows
- boxes

### PR DESCRIPTION
**Pull request by proxyconcept**
Can resolve #16 :
- The new config option $results_display_mode can be "boxes" (default) or "table".
- Two sub-templates are added : listing_boxes.tpl and listing_table.tpl, so the latter is shared with the directory view.
- When displaying search results with "table", columns are made from $search_result_title and $search_result_items.

Can partially resolve #1 :
- When displaying search results with "table", the Datatables JS component can be used for pagination
- New config option $use_datatables to enable/disable the Datatables component in the application
- New config option $datatables_page_length_choices (optional) to set the list of available page lengths
- New config option $datatables_page_length_default (previously named $default_page_length) to set the default page length for Datatables (can also be used to force the length without $databels_page_length_choices)
- But #1 can still stay opened because we can imagine another pagination system when search results are displayed in boxes

And as mentioned in #28 :
- Specific CSS style for links "mailto:" and "tel:"
- Config option $directory_linkto can also be a boolean value (instead of a list of columns) : true if you want the whole row clickable ; false do the same and hide the button in the first column.
- New config option $search_result_linkto : same as $directory_linkto for the search results in table.

Other new config options :
- $directory_show_undefined : same as $search_result_show_undefined for the display view.
- $display_show_undefined : same as $search_result_show_undefined for the display view.

Sorry for the big commits... It was hard to keep it smaller. I also made changes on smarty assignments in order to not load useless data and improve the factorization.

### CODE REVIEW

**Comment by coudot** [comment]
Thanks, I will need some time to review all the changes. I will try to do it as soon as possible.

**Comment by nqb** [comment]
Hello @proxyconcept,

> When displaying search results with "table", columns are made from $search_result_title and $search_result_items.

Do you use `$search_result_title` to keep compatibility with display view ? FYI, this variable is not use in directory view. It could be more consistent to have same display between two views.

> Specific CSS style for links "mailto:" and "tel:"

I notice that cursor is a **cross** when you move it on a mailto: or tel: link:
Expected behavior ?

> $directory_show_undefined : same as $search_result_show_undefined for the display view.

I suppose you would like to mean "directory view".

**Comment by nqb** [comment]
> New config option $datatables_page_length_choices (optional) to set the list of available page lengths

If I set 
```php
$datatables_page_length_choices = array(10, 25, 50, 100, 250, 500, -1);
```
I can't see this values in dropdown.

**Comment by proxyconcept** [comment]
> Do you use $search_result_title to keep compatibility with display view ?

I use $search_result_title and $search_result_items because they are used to construct the LDAP request. If we use another config options :
- $search_result_title and $search_result_items would become useless with $results_display_mode = 'table'
- It may be interesting to have different presentation between search results and directory view
- We can't use the config option $directory_items for search results display : it would be inconsistent especially when you don't use the directory view

So, I think we can :
- decide that the display is in all cases common between directory and results in table, then use a unique config option with an appropriate name
- keep a configuration for each view, for example with a new $search_result_columns (and rename $directory_items in $directory_columns)
- or just do with the current options... this is what I do with $search_result_title and $search_result_items

I don't say my actual solution is the best, but I can't decide on this point. So I chose the least impacting option.


> I notice that cursor is a cross when you move it on a mailto: or tel: link:

Yes... just because I wanted to use a different cursor than the classic pointer. it seems to me useful when the pointer cursor indicates that the link (or the entire row) is clickable to open the display view.
But unfortunately I found nothing better than the cross cursor in the standard cursors.


> I suppose you would like to mean "directory view".

Right... lazy copy/paste


> If I set $datatables_page_length_choices = array(10, 25, 50, 100, 250, 500, -1); I can't see this values in dropdown.

Well... It works for me

**Comment by nqb** [comment]
> If I set :
> 
> $datatables_page_length_choices = array(10, 25, 50, 100, 250, 500, -1);
> 
> I can't see 250 and 500 values in dropdown.

Sorry, it was an error. Great enhancement !

**Comment by coudot** [comment]
I will merge this PR and do some adaptations after.

**Pull request merged**
